# This holds the configuration for the backend of BeakleVision. This file is not settable during runtime.
# If you wish to change the values, change and save, and restart your server

beakle:

  # Host that the server will use.
  # Set to 0.0.0.0 if running in Docker
  host: "localhost"

  # Port that the server binds to.
  # Defaults to 8000
  port: 8000

api_keys:

  # TBA API Key
  tba: ""

# CockrocahDB connection URI used for connections
# See https://github.com/cockroachdb/sqlalchemy-cockroachdb/blob/master/README.asyncpg.md#asyncpg-support
cockroach_uri: "cockroachdb+asyncpg://root@localhost:26257/defaultdb"

# Valkey connection uri
valkey_uri: "valkey://localhost:6739/0"