name: beaklevision_dev

services:
  database:
    container_name: beaklevision_cockroach
    image: cockroachdb/cockroach:latest-v25.2
    hostname: beakle-roach
    environment:
      COCKROACH_PASSWORD: ${DB_PASSWORD}
      COCKROACH_DATABASE: ${DB_DATABASE}
      COCKROACH_USER: ${DB_USERNAME}
    env_file:
      - .env
    volumes:
      - "database:/cockroach/cockroach-data"
    command: "start-single-node --http-addr=beakle-roach:8080"
    ports:
      - 26257:26257
      - 8080:8080

  valkey:
    container_name: beaklevision_valkey
    image: valkey/valkey:8-alpine
    healthcheck:
      test: valkey-cli PING || exit 1
    ports:
      - 6379:6379
    
volumes:
  database:
