name: Test
on:
  push:
    branches: [dev]
    paths: [backend/src/**]
      
  pull_request:
    branches: [dev]
    paths: [backend/src/**]

jobs:
  backend:
    name: Test (Backend)
    runs-on: ubuntu-24.04

    defaults:
      run:
        working-directory: backend

    env:
      TESTCONTAINER_DOCKER_NETWORK: beaklevision-testcontainers

    steps:
      - name: Checkout Repository  
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Set up server configuration
        run: |
          cp config.dist.yml config.yml

      - name: Create Docker network for running Testcontainers
        run: sudo docker network create ${{ env.TESTCONTAINER_DOCKER_NETWORK }}

      - name: Install dependencies
        run: |
          pip install \
            "httpx>=0.28.1,<1" \
            "pytest>=8.4.0,<9" \
            "pytest-asyncio>=1.0.0,<2" \
            "testcontainers>=4.10.0,<5" \
            "asgi-lifespan>=2.1.0,<3" \
            -r requirements.txt

      - name: Test backend
        run: |
          pytest